# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
    - board: nice_nano
      shield: corne_left
    - board: nice_nano
      shield: corne_right
    - board: nice_nano_v2
      shield: corne_left
    - board: nice_nano_v2
      shield: corne_right
    - board: nice_nano
      shield: reviung41
      artifact-name: reviung41lp
      cmake-args: '-DDTC_OVERLAY_FILE="${GITHUB_WORKSPACE}/config/reviung41lp.keymap"'
    - board: nice_nano
      shield: kyria_left
    - board: nice_nano
      shield: kyria_right
    - board: nice_nano_v2
      shield: kyria_left
    - board: nice_nano_v2
      shield: kyria_right
    - board: nice_nano
      shield: reviung41
    - board: nice_nano_v2
      shield: reviung41
    - board: ahokore
    # my zaphod is a prototype and has different pins and I can't be arsed to figure it out at the moment
    # - board: zaphod
    - board: seeeduino_xiao
      shield: banana
    - board: nice_nano_v2
      shield: reviung34
    - board: nice_nano_v2
      shield: reviung34 nicehatharry nice_view
      artifact-name: reviung34_nice_view
    - board: nice_nano_v2
      shield: osprette
    # - board: nice_nano_v2
    #   shield: ffkb
    # - board: seeeduino_xiao
    #   shield: pdxkbc_macropad_xiao
    - board: nice_nano_v2
      shield: pdxkbc_macropad_promicro
