
#define DV_A A
#define DV_B N
#define DV_C I
#define DV_D H
#define DV_E D
#define DV_F Y
#define DV_G U
#define DV_H J
#define DV_I G
#define DV_J C
#define DV_K V
#define DV_L P
#define DV_M M
#define DV_N L
#define DV_O S
#define DV_P R
#define DV_Q X
#define DV_R O
#define DV_S SEMI
#define DV_T K
#define DV_U F
#define DV_V DOT
#define DV_W COMMA
#define DV_X B
#define DV_Y T
#define DV_Z FSLH
#define DV_SEMI Z
#define DV_SQT Q
#define DV_COMMA W
#define DV_DOT E
#define DV_FSLH LBKT
#define DV_QMARK LBRC
#define DV_MINUS SQT
#define DV_UNDER DQT
#define DV_EQUAL RBKT
#define DV_PLUS RBRC
#define DV_LBKT MINUS
#define DV_RBKT EQUAL
#define DV_LBRC UNDER
#define DV_RBRC PLUS

