manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kitchen
      url-base: https://github.com/kitchen
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nicehatharry
      remote: kitchen
      clone-depth: 1
      revision: kitchen/zmk-shield
    - name: reviung34
      remote: reviung34-zmk
      clone-depth: 1
      revision: main
  self:
    path: config
