manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohansen
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: core/zephyr-main-rp2040-playground
      import: app/west.yml
  self:
    path: config
